# Generated by Django 2.2.5 on 2020-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrolled',
            field=models.ManyToManyField(related_name='enrolled', to='rooms.Room'),
        ),
    ]
