# Generated by Django 2.2.5 on 2020-11-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('start_date', models.DateField(default=False)),
                ('end_date', models.DateField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('evidence_text', models.CharField(blank=True, max_length=300)),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TodoPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(default='')),
                ('file', models.ImageField(upload_to='evidence_photos')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_photos', to='todos.Todo')),
            ],
        ),
    ]
