# Generated by Django 2.2.5 on 2020-11-23 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='rooms.Room'),
        ),
    ]
