# Generated by Django 2.2.5 on 2020-11-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_host'),
        ('todos', '0003_auto_20201123_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='rooms',
        ),
        migrations.AddField(
            model_name='todo',
            name='rooms',
            field=models.ManyToManyField(related_name='todos', to='rooms.Room'),
        ),
    ]
